version: "2"

volumes:
  node_modules:
services:
  mysql:
    build: ./database
  discounts-api:
    build: ./discounts
    environment:
      APP_NAME: "discounts-api"
      APP_ENV: "development"
      LOG_LEVEL: "INFO"
      DB_HOST: "database"
      DB_DATABASE: "api"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      GRPC_PORT: "5001"
    ports:
      - "5001:5001"
    links:
      - mysql:database    
  products-api:
    build: ./products
    environment:
      APP_NAME: "products-api"
      APP_ENV: "development"
      LOG_LEVEL: "INFO"
      DB_HOST: "database"
      DB_DATABASE: "api"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      GRPC_PORT: "5002"
      HTTP_PORT: "80"
      DISCOUNTS_PORT: "5001"
      DISCOUNTS_ADDRESS: "discounts"
    ports:
      - "8080:80"
      - "5002:5002"
    links:
      - mysql:database
      - discounts-api:discounts
