version: "2"

volumes:
  node_modules:
services:
  mysql:
    build: ../database
  api:
    build: .
    environment:
      APP_NAME: "products-api"
      APP_ENV: "development"
      LOG_LEVEL: "INFO"
      DB_HOST: "database"
      DB_DATABASE: "api"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      HTTP_PORT: "80"
      GRPC_PORT: "5002"
      DISCOUNTS_PORT: "5001"
      DISCOUNTS_ADDRESS: "0.0.0.0"
    volumes:
      - ./:/server
      - node_modules:/server/node_modules
    ports:
      - "8080:80"
      - "5002:5002"
    links:
      - mysql:database
