steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['clean', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/discounts-api:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discounts-api:$COMMIT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/discounts-api:$COMMIT_SHA'
